using UnityEngine;
using UnityEngine.UI;

public class RubyController : MonoBehaviour
{
    float speed = 3.0f;

    Animator animator;
    Rigidbody2D rigidbody2d;

    float horizontal;
    float vertical;

    Vector2 lookDirection = new Vector2(0, 0);

    public int maxHealth = 100;
    int currentHealth;

    // Timer for damage
    float timeInvincible = 1.0f;
    bool isInvincible;
    float invincibleTimer;

    public GameObject projectilePrefab;
    
    AudioSource audioSource;
    public AudioClip throwSound;
    public AudioClip hitSound;
    public Image healthBar;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        animator = GetComponent<Animator>();
        rigidbody2d = GetComponent<Rigidbody2D>();
        audioSource = GetComponent<AudioSource>();
        currentHealth = 100;
        UpdateHealthBarUI();
    }

    // Update is called once per frame
    void Update()
    {
        horizontal = Input.GetAxis("Horizontal");
        vertical = Input.GetAxis("Vertical");

        // Animation parameters
        Vector2 move = new Vector2(horizontal, vertical);
        if (!Mathf.Approximately(move.x, 0.0f) || !Mathf.Approximately(move.y, 0.0f))
        {
            lookDirection.Set(move.x, move.y);
            lookDirection.Normalize();
        }

        animator.SetFloat("Look X", lookDirection.x);
        animator.SetFloat("Look Y", lookDirection.y);
        animator.SetFloat("Speed", move.magnitude);
        // Debug.Log("Speed: " + move.magnitude.ToString());

        if (isInvincible)
        {
            invincibleTimer -= Time.deltaTime;
            if (invincibleTimer < 0)
            {
                isInvincible = false;
            }
        }

        if (Input.GetKeyDown(KeyCode.C))
        {
            LaunchProjectile();
        }

        if (Input.GetKeyDown(KeyCode.X))
        {
            RaycastHit2D hit = Physics2D.Raycast(transform.position, lookDirection, 1.5f, LayerMask.GetMask("NPC"));
            if (hit.collider != null)
            {
                Debug.Log("Raycast hit " + hit.collider.gameObject.name);
                NPC npc = hit.collider.GetComponent<NPC>();
                if (npc != null)
                {
                    npc.showDialog();
                }
            }   
        }
    }

    void FixedUpdate()
    {
        Vector2 position = rigidbody2d.position;
        position.x = position.x + speed * horizontal * Time.deltaTime;
        position.y = position.y + speed * vertical * Time.deltaTime;

        rigidbody2d.MovePosition(position);
    }

    // Change health method
    public void ChangeHealth(int amount)
    {
        if (amount < 0)
        {
            if (isInvincible)
                return;

            animator.SetTrigger("Hit");
            PlaySound(hitSound);

            isInvincible = true;
            invincibleTimer = timeInvincible;
        }

        currentHealth = Mathf.Clamp(currentHealth + amount, 0, maxHealth);
        UpdateHealthBarUI();
        Debug.Log("Health: " + currentHealth.ToString());
    }

    void LaunchProjectile()
    {
        GameObject projectileObject = Instantiate(projectilePrefab, rigidbody2d.position + Vector2.up * 0.2f   , Quaternion.identity);

        Projectile projectile = projectileObject.GetComponent<Projectile>();
        projectile.Launch(lookDirection, 300);
        
        animator.SetTrigger("Launch");
        PlaySound(throwSound);
    }

    public void PlaySound(AudioClip clip)
    {
        audioSource.PlayOneShot(clip);
    }

    public void UpdateHealthBarUI()
    {
        float healthRatio = (float)currentHealth / (float)maxHealth;
        healthBar.fillAmount = healthRatio;
    }
}
